/* Generated by vite.config.js (suuraseikkailu-sw) – do not edit. */
'use strict';
const VERSION = "5c8a292ae02adaca";
const FILES = [
 "index.html",
 "assets/amiri-quran-arabic-400-normal-CZ144KtP.woff",
 "assets/amiri-quran-arabic-400-normal-wRcqfVJx.woff2",
 "assets/fredoka-latin-500-normal-B0JifZgm.woff2",
 "assets/fredoka-latin-500-normal-BL692wg7.woff",
 "assets/fredoka-latin-600-normal-C4zohCW5.woff2",
 "assets/fredoka-latin-600-normal-CcrEjrB4.woff",
 "assets/fredoka-latin-700-normal-BOIZVyIN.woff2",
 "assets/fredoka-latin-700-normal-C8FeHd3X.woff",
 "assets/index-DfxWd6M3.js",
 "assets/index-wjU-CDnM.css",
 "assets/nunito-latin-400-normal-DKg4f3fz.woff",
 "assets/nunito-latin-400-normal-r8SDr6Up.woff2",
 "assets/nunito-latin-700-normal-Dort48En.woff2",
 "assets/nunito-latin-700-normal-OcDqTBcA.woff",
 "assets/nunito-latin-800-normal-D-J0wlBY.woff",
 "assets/nunito-latin-800-normal-Dz8SOQK_.woff2",
 "audio/001001.mp3",
 "audio/001002.mp3",
 "audio/001003.mp3",
 "audio/001004.mp3",
 "audio/001005.mp3",
 "audio/001006.mp3",
 "audio/001007.mp3",
 "audio/108001.mp3",
 "audio/108002.mp3",
 "audio/108003.mp3",
 "audio/112001.mp3",
 "audio/112002.mp3",
 "audio/112003.mp3",
 "audio/112004.mp3",
 "audio/fi/ask-theme.mp3",
 "audio/fi/cover.mp3",
 "audio/fi/finale-fatiha.mp3",
 "audio/fi/finale-ikhlas.mp3",
 "audio/fi/finale-kawthar.mp3",
 "audio/fi/finale-shahada.mp3",
 "audio/fi/game-boy-0.mp3",
 "audio/fi/game-boy-1.mp3",
 "audio/fi/game-boy-2.mp3",
 "audio/fi/game-boy-3.mp3",
 "audio/fi/game-boy-4.mp3",
 "audio/fi/game-boy-5.mp3",
 "audio/fi/game-girl-0.mp3",
 "audio/fi/game-girl-1.mp3",
 "audio/fi/game-girl-2.mp3",
 "audio/fi/game-girl-3.mp3",
 "audio/fi/game-girl-4.mp3",
 "audio/fi/game-girl-5.mp3",
 "audio/fi/gem.mp3",
 "audio/fi/level-easy.mp3",
 "audio/fi/level-hard.mp3",
 "audio/fi/level-medium.mp3",
 "audio/fi/listen.mp3",
 "audio/fi/mean-fatiha-0.mp3",
 "audio/fi/mean-fatiha-1.mp3",
 "audio/fi/mean-fatiha-2.mp3",
 "audio/fi/mean-fatiha-3.mp3",
 "audio/fi/mean-fatiha-4.mp3",
 "audio/fi/mean-fatiha-5.mp3",
 "audio/fi/mean-fatiha-6.mp3",
 "audio/fi/mean-ikhlas-0.mp3",
 "audio/fi/mean-ikhlas-1.mp3",
 "audio/fi/mean-ikhlas-2.mp3",
 "audio/fi/mean-ikhlas-3.mp3",
 "audio/fi/mean-ikhlas-4.mp3",
 "audio/fi/mean-kawthar-0.mp3",
 "audio/fi/mean-kawthar-1.mp3",
 "audio/fi/mean-kawthar-2.mp3",
 "audio/fi/mean-kawthar-3.mp3",
 "audio/fi/mean-shahada-0.mp3",
 "audio/fi/mean-shahada-1.mp3",
 "audio/fi/next.mp3",
 "audio/fi/pick-level.mp3",
 "audio/fi/praise-1.mp3",
 "audio/fi/praise-2.mp3",
 "audio/fi/praise-3.mp3",
 "audio/fi/praise-4.mp3",
 "audio/fi/praise-5.mp3",
 "audio/fi/rocket-launch.mp3",
 "audio/fi/rocket-part.mp3",
 "audio/fi/sticker.mp3",
 "audio/fi/test-fi.mp3",
 "audio/fi/turn-1.mp3",
 "audio/fi/turn-all.mp3",
 "audio/fi/welcome.mp3",
 "audio/fi/who.mp3",
 "audio/shahada-1.mp3",
 "audio/shahada-2.mp3",
 "audio/shahada-c-1-easy-1.mp3",
 "audio/shahada-c-1-easy-2.mp3",
 "audio/shahada-c-1-easy-3.mp3",
 "audio/shahada-c-1-easy-4.mp3",
 "audio/shahada-c-1-medium-1.mp3",
 "audio/shahada-c-1-medium-2.mp3",
 "audio/shahada-c-2-easy-1.mp3",
 "audio/shahada-c-2-easy-2.mp3",
 "audio/shahada-c-2-easy-3.mp3",
 "audio/shahada-c-2-easy-4.mp3",
 "audio/shahada-c-2-easy-5.mp3",
 "audio/shahada-c-2-medium-1.mp3",
 "audio/shahada-c-2-medium-2.mp3",
 "audio/shahada-c-2-medium-3.mp3",
 "audio/wbw/001_001_001.mp3",
 "audio/wbw/001_001_002.mp3",
 "audio/wbw/001_001_003.mp3",
 "audio/wbw/001_001_004.mp3",
 "audio/wbw/001_002_001.mp3",
 "audio/wbw/001_002_002.mp3",
 "audio/wbw/001_002_003.mp3",
 "audio/wbw/001_002_004.mp3",
 "audio/wbw/001_003_001.mp3",
 "audio/wbw/001_003_002.mp3",
 "audio/wbw/001_004_001.mp3",
 "audio/wbw/001_004_002.mp3",
 "audio/wbw/001_004_003.mp3",
 "audio/wbw/001_005_001.mp3",
 "audio/wbw/001_005_002.mp3",
 "audio/wbw/001_005_003.mp3",
 "audio/wbw/001_005_004.mp3",
 "audio/wbw/001_006_001.mp3",
 "audio/wbw/001_006_002.mp3",
 "audio/wbw/001_006_003.mp3",
 "audio/wbw/001_007_001.mp3",
 "audio/wbw/001_007_002.mp3",
 "audio/wbw/001_007_003.mp3",
 "audio/wbw/001_007_004.mp3",
 "audio/wbw/001_007_005.mp3",
 "audio/wbw/001_007_006.mp3",
 "audio/wbw/001_007_007.mp3",
 "audio/wbw/001_007_008.mp3",
 "audio/wbw/001_007_009.mp3",
 "audio/wbw/108_001_001.mp3",
 "audio/wbw/108_001_002.mp3",
 "audio/wbw/108_001_003.mp3",
 "audio/wbw/108_002_001.mp3",
 "audio/wbw/108_002_002.mp3",
 "audio/wbw/108_002_003.mp3",
 "audio/wbw/108_003_001.mp3",
 "audio/wbw/108_003_002.mp3",
 "audio/wbw/108_003_003.mp3",
 "audio/wbw/108_003_004.mp3",
 "audio/wbw/112_001_001.mp3",
 "audio/wbw/112_001_002.mp3",
 "audio/wbw/112_001_003.mp3",
 "audio/wbw/112_001_004.mp3",
 "audio/wbw/112_002_001.mp3",
 "audio/wbw/112_002_002.mp3",
 "audio/wbw/112_003_001.mp3",
 "audio/wbw/112_003_002.mp3",
 "audio/wbw/112_003_003.mp3",
 "audio/wbw/112_003_004.mp3",
 "audio/wbw/112_004_001.mp3",
 "audio/wbw/112_004_002.mp3",
 "audio/wbw/112_004_003.mp3",
 "audio/wbw/112_004_004.mp3",
 "audio/wbw/112_004_005.mp3",
 "icons/apple-touch-icon.png",
 "icons/favicon-32.png",
 "icons/icon-192.png",
 "icons/icon-512.png",
 "icons/icon-maskable-512.png",
 "manifest.webmanifest"
];

/* Suuraseikkailu service worker runtime. OWNER: pwa agent.
 *
 * Not loaded directly: the 'suuraseikkailu-sw' plugin in vite.config.js prepends
 *     const VERSION = '<hash of every file in dist>';
 *     const FILES = ['index.html', 'assets/…', 'audio/…', …];   // relative to sw.js
 * and writes the result to dist/sw.js after each build. Classic worker script: no imports.
 *
 * install  : download every file of this build into a new cache (3 tries per file). If one file
 *            still fails, the new cache is deleted and install fails, so the previous version (or
 *            plain online use) stays in charge; the browser tries again on the next visit.
 *            skipWaiting(): a new version takes over without a reload under the child.
 * activate : delete older caches of this same app folder, clients.claim().
 * fetch    : same-origin GET inside our folder -> cache first, network fallback (successful
 *            responses are stored). Navigations -> cached page, offline -> cached index.html.
 *            Range requests (iOS Safari media) -> 206 Partial Content sliced from the cached file.
 *            Cross-origin requests are left to the browser.
 * ('use strict' is emitted by the generator, as the first statement of sw.js.)
 */

var SCOPE = self.registration.scope;                 // e.g. https://host/sub/suuraseikkailu/
var CACHE_BASE = 'suuraseikkailu:' + SCOPE + ':';    // one app folder = one cache family
var CACHE = CACHE_BASE + VERSION;
var INDEX_URL = new URL('index.html', self.location.href).href;
var TRIES = 3;
var PARALLEL = 4;

function noop() {}
function sleep(ms) { return new Promise(function (r) { setTimeout(r, ms); }); }

// Navigations must not be answered with a redirected response (Cloudflare Pages redirects
// /index.html -> /), so such responses are stored as plain copies.
async function plain(res) {
  if (!res.redirected) return res;
  var body = await res.blob();
  return new Response(body, { status: res.status, statusText: res.statusText, headers: res.headers });
}

async function download(url) {
  var lastErr = null;
  for (var attempt = 0; attempt < TRIES; attempt++) {
    if (attempt) await sleep(attempt * 800);
    try {
      var res = await fetch(new Request(url, { cache: 'reload', credentials: 'same-origin' }));
      if (res.status === 200) return await plain(res);
      lastErr = new Error('HTTP ' + res.status + ' ' + url);
    } catch (e) {
      lastErr = e;
    }
  }
  throw lastErr;
}

async function precache() {
  var cache = await caches.open(CACHE);
  var queue = FILES.slice();
  var failure = null;
  async function worker() {
    while (queue.length && !failure) {
      var url = new URL(queue.shift(), self.location.href).href;
      try {
        if (await cache.match(url)) continue;        // already stored by an interrupted install
        await cache.put(url, await download(url));
      } catch (e) {
        failure = failure || e;
      }
    }
  }
  var workers = [];
  for (var i = 0; i < PARALLEL; i++) workers.push(worker());
  await Promise.all(workers);
  if (!failure) {
    // the bare folder URL (start_url './') opens the same page
    var index = await cache.match(INDEX_URL);
    if (index) await cache.put(SCOPE, index);
    else failure = new Error('index.html missing from precache');
  }
  if (failure) {
    await caches.delete(CACHE);                       // never leave a half-filled version behind
    throw failure;
  }
}

self.addEventListener('install', function (event) {
  self.skipWaiting();
  event.waitUntil(precache());
});

self.addEventListener('activate', function (event) {
  event.waitUntil((async function () {
    var names = await caches.keys();
    await Promise.all(names.map(function (name) {
      return name !== CACHE && name.indexOf(CACHE_BASE) === 0 ? caches.delete(name) : null;
    }));
    await self.clients.claim();
  })());
});

async function fromCache(cache, req, opts) {
  try { return await cache.match(req, opts); } catch (e) { return undefined; }
}

function store(event, cache, key, res) {
  if (res.status !== 200 || res.type !== 'basic') return;
  var copy = res.clone();
  var job = plain(copy).then(function (r) { return cache.put(key, r); }).catch(noop);
  try { event.waitUntil(job); } catch (e) { /* event already finished: the put still runs */ }
}

async function cacheFirst(event) {
  var req = event.request;
  var cache = await caches.open(CACHE);
  var hit = await fromCache(cache, req, { ignoreVary: true });
  if (hit) return hit;
  var res = await fetch(req);
  store(event, cache, req, res);
  return res;
}

async function navigate(event) {
  var req = event.request;
  var cache = await caches.open(CACHE);
  var hit = await fromCache(cache, req, { ignoreSearch: true, ignoreVary: true });
  if (hit) return hit;
  try {
    return await fetch(req);
  } catch (e) {
    // offline and not cached: open the app. Deeper paths are redirected to the app folder so the
    // page's relative URLs (./assets/…) still point into the cache.
    var index = await fromCache(cache, INDEX_URL, { ignoreVary: true });
    if (!index) throw e;
    var dir = req.url.split(/[?#]/)[0].replace(/[^/]*$/, '');
    return dir === SCOPE ? index : Response.redirect(SCOPE, 302);
  }
}

// RFC 9110 single byte range: "bytes=a-b", "bytes=a-", "bytes=-n" (only the first of a list).
function parseRange(header, size) {
  var m = /^\s*bytes\s*=\s*(\d*)\s*-\s*(\d*)\s*(?:,|$)/i.exec(header || '');
  if (!m || (m[1] === '' && m[2] === '')) return null;            // unusable header -> full file
  var start, end;
  if (m[1] === '') {
    var n = parseInt(m[2], 10);
    if (!n) return { bad: true };
    start = Math.max(0, size - n);
    end = size - 1;
  } else {
    start = parseInt(m[1], 10);
    end = m[2] === '' ? size - 1 : Math.min(parseInt(m[2], 10), size - 1);
  }
  if (start >= size || end < start) return { bad: true };
  return { start: start, end: end };
}

async function partial(full, header) {
  var blob = await full.blob();
  var size = blob.size;
  var type = full.headers.get('Content-Type') || blob.type || 'application/octet-stream';
  var r = parseRange(header, size);
  var headers = new Headers({ 'Content-Type': type, 'Accept-Ranges': 'bytes' });
  if (!r) {
    headers.set('Content-Length', String(size));
    return new Response(blob, { status: 200, statusText: 'OK', headers: headers });
  }
  if (r.bad) {
    headers.set('Content-Range', 'bytes */' + size);
    return new Response(null, { status: 416, statusText: 'Range Not Satisfiable', headers: headers });
  }
  headers.set('Content-Range', 'bytes ' + r.start + '-' + r.end + '/' + size);
  headers.set('Content-Length', String(r.end - r.start + 1));
  return new Response(blob.slice(r.start, r.end + 1), { status: 206, statusText: 'Partial Content', headers: headers });
}

async function ranged(event) {
  var req = event.request;
  var cache = await caches.open(CACHE);
  var full = await fromCache(cache, req.url, { ignoreVary: true });
  if (!full) {
    // not cached yet: fetch the whole file once (no Range), keep it, then answer the range
    full = await fetch(req.url, { credentials: 'same-origin' });
    if (full.status !== 200) return full;
    store(event, cache, req.url, full);
  }
  return partial(full, req.headers.get('Range'));
}

self.addEventListener('fetch', function (event) {
  var req = event.request;
  if (req.method !== 'GET') return;
  if (req.url.indexOf(SCOPE) !== 0) return;          // cross-origin or outside our folder
  if (req.cache === 'only-if-cached' && req.mode !== 'same-origin') return;
  if (req.headers.has('Range')) event.respondWith(ranged(event));
  else if (req.mode === 'navigate') event.respondWith(navigate(event));
  else event.respondWith(cacheFirst(event));
});
