// Build config. OWNER: pwa agent.
// base './' keeps every URL relative, so the built dist/ works from any folder or sub-path (zip delivery).
// Plugin 'suuraseikkailu-sw': after the bundle is written it generates dist/sw.js = the runtime in
// tools/pwa-sw.cjs + a precache list of every file in dist + a cache version hashed from their contents.
import { defineConfig } from 'vite';
import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const SW_FILE = 'sw.js';
const SW_RUNTIME = 'tools/pwa-sw.cjs';

// every file below dir as 'a/b.ext' (posix), skipping dotfiles and the service worker itself
function listFiles(dir, prefix = '') {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;
    const rel = prefix + entry.name;
    if (entry.isDirectory()) out.push(...listFiles(join(dir, entry.name), rel + '/'));
    else if (entry.isFile() && rel !== SW_FILE) out.push(rel);
  }
  return out;
}

function serviceWorker() {
  let config;
  return {
    name: 'suuraseikkailu-sw',
    apply: 'build',
    configResolved(resolved) {
      config = resolved;
    },
    closeBundle() {
      const outDir = resolve(config.root, config.build.outDir);
      if (!existsSync(join(outDir, 'index.html'))) return; // failed build: nothing to precache
      const runtime = readFileSync(resolve(config.root, SW_RUNTIME), 'utf8');
      const files = listFiles(outDir).sort((a, b) => (a === 'index.html' ? -1 : b === 'index.html' ? 1 : a < b ? -1 : 1));
      const hash = createHash('sha256').update(runtime);
      for (const file of files) hash.update(file + '\0').update(readFileSync(join(outDir, file))).update('\0');
      const version = hash.digest('hex').slice(0, 16);
      const urls = files.map((f) => f.split('/').map(encodeURIComponent).join('/'));
      const head = '/* Generated by vite.config.js (suuraseikkailu-sw) – do not edit. */\n' +
        "'use strict';\n" +
        'const VERSION = ' + JSON.stringify(version) + ';\n' +
        'const FILES = ' + JSON.stringify(urls, null, 1) + ';\n\n';
      writeFileSync(join(outDir, SW_FILE), head + runtime);
      config.logger.info(`\n${SW_FILE}: ${files.length} files precached, cache version ${version}`);
    }
  };
}

export default defineConfig({
  base: './',
  build: { target: 'es2019', assetsInlineLimit: 0 },
  plugins: [serviceWorker()]
});
