/* Service worker registration. OWNER: pwa agent.
   registerSW() registers ./sw.js (generated by vite.config.js at build time) in production builds only,
   scope './' = the folder the app is served from, so it works offline from any sub-path.
   Optional: registerSW({ onOfflineReady }) – called once the whole app is stored on the device.
   Silent on every error: without a service worker the app works the same, just not offline. */

const UPDATE_CHECK_MS = 5 * 60 * 1000;

/* A new version took over: reload once the child is not in the middle of a lesson, game or the parent sheet. */
function safeToReload() {
  const html = document.documentElement;
  if (html.classList.contains('in-learn') || html.classList.contains('settings-open')) return false;
  const game = document.querySelector('.mg');
  return !(game && !game.hidden);
}
let started = false;

export function registerSW(options) {
  if (started || !import.meta.env.PROD) return;
  started = true;
  const onOfflineReady = options && typeof options.onOfflineReady === 'function' ? options.onOfflineReady : null;
  let container = null;
  try {
    if (window.isSecureContext) container = navigator.serviceWorker || null; // https or localhost only
  } catch (e) { /* blocked (sandboxed frame, private mode) */ }
  if (!container) return;

  const start = () => {
    let registration = null;
    let lastCheck = Date.now();
    // first install (no controller yet) must not reload; a later take-over means a new version is active
    const hadController = !!container.controller;
    let pending = false, timer = 0;
    const reloadWhenSafe = () => {
      if (safeToReload()) { clearInterval(timer); window.location.reload(); }
    };
    container.addEventListener('controllerchange', () => {
      if (!hadController || pending) return;
      pending = true;
      reloadWhenSafe();
      if (pending) timer = setInterval(reloadWhenSafe, 4000);
    });
    container.register('./sw.js', { scope: './', updateViaCache: 'none' })
      .then((reg) => { registration = reg; return container.ready; })
      .then(() => { if (onOfflineReady) onOfflineReady(); })
      .catch(() => {});
    // A tablet may keep the app open for days: look for a new version when it returns to the foreground.
    // The new version installs in the background, takes over, and the page reloads at a safe moment
    // (cover, picker or home) – never in the middle of a lesson or a game.
    document.addEventListener('visibilitychange', () => {
      if (document.visibilityState !== 'visible' || !registration || Date.now() - lastCheck < UPDATE_CHECK_MS) return;
      lastCheck = Date.now();
      registration.update().catch(() => {});
    });
  };
  if (document.readyState === 'complete') start();
  else window.addEventListener('load', start, { once: true });
}
