/* Service worker registration. OWNER: pwa agent.
   registerSW() registers ./sw.js (generated by vite.config.js at build time) in production builds only,
   scope './' = the folder the app is served from, so it works offline from any sub-path.
   Optional: registerSW({ onOfflineReady }) – called once the whole app is stored on the device.
   Silent on every error: without a service worker the app works the same, just not offline. */

const UPDATE_CHECK_MS = 60 * 60 * 1000;
let started = false;

export function registerSW(options) {
  if (started || !import.meta.env.PROD) return;
  started = true;
  const onOfflineReady = options && typeof options.onOfflineReady === 'function' ? options.onOfflineReady : null;
  let container = null;
  try {
    if (window.isSecureContext) container = navigator.serviceWorker || null; // https or localhost only
  } catch (e) { /* blocked (sandboxed frame, private mode) */ }
  if (!container) return;

  const start = () => {
    let registration = null;
    let lastCheck = Date.now();
    container.register('./sw.js', { scope: './', updateViaCache: 'none' })
      .then((reg) => { registration = reg; return container.ready; })
      .then(() => { if (onOfflineReady) onOfflineReady(); })
      .catch(() => {});
    // A tablet may keep the app open for days: look for a new version when it returns to the foreground.
    // The new version installs in the background and is used from the next start (never a reload mid-play).
    document.addEventListener('visibilitychange', () => {
      if (document.visibilityState !== 'visible' || !registration || Date.now() - lastCheck < UPDATE_CHECK_MS) return;
      lastCheck = Date.now();
      registration.update().catch(() => {});
    });
  };
  if (document.readyState === 'complete') start();
  else window.addEventListener('load', start, { once: true });
}
